import { FileText, LockKeyhole, Scale } from 'lucide-react'
import { LegalPage, type PageSection } from './CompanyPageShell'

const privacy: PageSection[] = [
  { id: 'information-we-collect', title: 'Information We Collect', content: <p>We may collect personal information such as your name, email address, mobile number, address, financial details, and other information required for providing our services.</p> },
  { id: 'how-we-use-information', title: 'How We Use Information', content: <p>Your information is used for customer verification, loan assistance services, customer support, payment processing, and improving our website experience.</p> },
  { id: 'payment-security', title: 'Payment Security', content: <p>All transactions are processed through secure payment gateway providers. We do not store your debit card, credit card, UPI PIN, or banking passwords.</p> },
  { id: 'information-sharing', title: 'Information Sharing', content: <p>We do not sell your personal data. Information may be shared only with banking partners, verification agencies, service providers, or legal authorities when required to deliver a requested service or comply with law.</p> },
  { id: 'cookies', title: 'Cookies', content: <p>Our website may use cookies and similar technologies to improve user experience, remember preferences, maintain secure sessions, and analyse website traffic.</p> },
  { id: 'data-protection', title: 'Data Protection', content: <p>We implement appropriate administrative, technical, and organisational security measures to protect user information from unauthorised access, misuse, alteration, or disclosure.</p> },
  { id: 'third-party-links', title: 'Third-Party Links', content: <p>Our website may contain third-party links. We are not responsible for the privacy practices, availability, or content of external websites.</p> },
  { id: 'user-consent', title: 'User Consent', content: <p>By using our website and services, you consent to this Privacy Policy and the processing needed to respond to your requests.</p> },
  { id: 'policy-updates', title: 'Policy Updates', content: <p>AV Management Pvt Ltd reserves the right to modify this Privacy Policy. Material updates will be published on this page with a revised update date.</p> },
  { id: 'contact-information', title: 'Contact Information', content: <div className="legal-contact-lines"><p><strong>Company:</strong> AV Management Pvt Ltd</p><p><strong>Email:</strong> info@avmanagement.in</p><p><strong>Phone:</strong> +91 99175 00023</p><p><strong>Website:</strong> avmanagementpvtltd.com</p></div> },
]

const terms: PageSection[] = [
  { id: 'acceptance', title: 'Acceptance of Terms', content: <p>By accessing or using this website, creating an account, requesting a report, applying for a financial product, or making a payment, you agree to these Terms and Conditions and our Privacy Policy.</p> },
  { id: 'services', title: 'Our Services', content: <p>AV Management provides access to financial-product information, loan assistance, credit-report and score-related services, insurance and investment journeys, verification support, and other digital financial services shown on the website. Product availability and eligibility may vary.</p> },
  { id: 'eligibility', title: 'Eligibility and Account Responsibility', content: <p>You must provide accurate, current, and complete information. You are responsible for protecting your login credentials, OTPs, devices, and account activity. Do not allow another person to impersonate you or submit information without authority.</p> },
  { id: 'applications', title: 'Applications and Approvals', content: <p>Submitting an enquiry or application does not guarantee approval, a particular rate, credit limit, policy issuance, or disbursal. Final decisions are made by the relevant bank, NBFC, insurer, credit bureau, or service partner under its own policies.</p> },
  { id: 'payments', title: 'Payments and Wallet', content: <p>Paid services and wallet top-ups are processed through authorised payment providers. Charges, taxes, minimum amounts, and service prices are displayed before confirmation where applicable. A transaction is complete only after successful confirmation by the payment and backend systems.</p> },
  { id: 'permitted-use', title: 'Permitted Use', content: <p>You must not misuse the website, attempt unauthorised access, upload malicious content, interfere with security controls, scrape protected data, use another person’s identity, or use reports and services for unlawful purposes.</p> },
  { id: 'third-parties', title: 'Third-Party Products and Links', content: <p>Some services are provided by third parties. Their product terms, underwriting rules, fees, privacy practices, and service availability may apply separately. Please review the relevant partner documents before proceeding.</p> },
  { id: 'intellectual-property', title: 'Intellectual Property', content: <p>The website design, brand assets, original copy, software, and other protected material belong to AV Management or their respective licensors. They may not be copied, republished, or commercially exploited without permission.</p> },
  { id: 'limitation', title: 'Disclaimer and Limitation', content: <p>Information on this website is general and does not replace personalised legal, tax, investment, or financial advice. To the extent permitted by law, AV Management is not responsible for losses caused by unauthorised account use, third-party failures, inaccurate user information, or circumstances beyond reasonable control.</p> },
  { id: 'changes-contact', title: 'Changes and Contact', content: <p>We may update these terms to reflect service, legal, or operational changes. Continued use after an update means the revised terms apply. Questions can be sent to contact@avmanagement.in or raised through our Contact Us page.</p> },
]

const disclosures: PageSection[] = [
  { id: 'role', title: 'Our Role', content: <p>AV Management helps customers explore and access financial services. Depending on the journey, we may act as a facilitator, technology interface, assistance provider, or service intermediary. We do not represent that every product is suitable for every customer.</p> },
  { id: 'no-guarantee', title: 'No Guarantee of Approval', content: <p>Displayed offers, estimates, eligibility indicators, processing timelines, and rates are illustrative or subject to verification. Approval, pricing, policy issuance, credit limits, and disbursal remain subject to the relevant provider’s assessment.</p> },
  { id: 'credit-information', title: 'Credit Information Services', content: <p>Credit scores and reports are based on information maintained or supplied by the relevant credit information company or authorised service provider. AV Management does not independently create bureau data and cannot guarantee that third-party records are free from errors.</p> },
  { id: 'insurance-products', title: 'Insurance and Investment Products', content: <p>Insurance is a contract between the policyholder and insurer. Investment values and benefits depend on the selected product and its official documents. Customers should review benefits, exclusions, risks, charges, and policy wording before purchase.</p> },
  { id: 'fees', title: 'Fees, Payments and Commercial Relationships', content: <p>Certain digital reports, verification services, or assistance journeys may carry a displayed fee. AV Management may receive service fees or compensation from partners where permitted. This does not change the customer’s responsibility to evaluate the product.</p> },
  { id: 'customer-duty', title: 'Customer Responsibility', content: <p>Customers should provide truthful information, review all documents, protect OTPs and account access, and independently confirm important product terms. Never make a payment to an unauthorised personal account or share banking passwords or UPI PINs.</p> },
  { id: 'accuracy', title: 'Website Information', content: <p>We work to keep website information current, but product terms can change. In the event of a difference, the official document issued by the bank, NBFC, insurer, bureau, payment provider, or other regulated entity will prevail.</p> },
  { id: 'support', title: 'Questions and Support', content: <p>For questions about a displayed service, transaction, or disclosure, contact us before proceeding at +91 99175 00023 or contact@avmanagement.in.</p> },
]

export const PrivacyPolicyPage = () => <LegalPage eyebrow="Your data, treated responsibly" title="Privacy Policy" description="Clear information about what we collect, why we use it, and how we work to keep it protected." icon={LockKeyhole} sections={privacy} note="AV Management Pvt Ltd values your privacy and is committed to protecting your personal information." />
export const TermsConditionsPage = () => <LegalPage eyebrow="Clear expectations" title="Terms & Conditions" description="The rules that help keep our website, services, applications, and payments safe and transparent." icon={Scale} sections={terms} note="Please read these terms before using AV Management’s website or digital services." />
export const DisclosurePage = () => <LegalPage eyebrow="Transparency first" title="Important Disclosures" description="Understand our role, third-party product decisions, service fees, and your responsibilities before proceeding." icon={FileText} sections={disclosures} note="Read this disclosure with the applicable product documents, Terms & Conditions, and Privacy Policy." />
