import { useState } from 'react'
import { CalendarDays, ChevronLeft, ChevronRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import { creditArticles } from '../components/credit-score/CreditScoreArticles'

export default function CreditScoreArticlesPage() {
  const [page, setPage] = useState(1)
  const perPage = 8
  const pages = Math.ceil(creditArticles.length / perPage)
  const articles = creditArticles.slice((page - 1) * perPage, page * perPage)
  return <main className="min-h-screen bg-white"><div className="border-y border-slate-200 bg-slate-50"><div className="container-pb flex flex-wrap items-center justify-between gap-3 py-5"><h1 className="font-serif text-3xl font-bold text-navy">Category: Credit Score</h1><p className="text-sm text-slate-500"><Link to="/" className="text-blue-600 hover:underline">Home</Link> / Credit Score / Page {page}</p></div></div><div className="container-pb py-10"><p className="max-w-2xl text-slate-600">Explore expert articles on credit reports, credit scores and practical habits for a healthier financial profile.</p><div className="mt-8 space-y-8">{articles.map((article) => <Link to={`/category/credit-score/${article.slug}`} key={article.slug} className="group grid gap-5 border-b border-slate-200 pb-8 md:grid-cols-[330px_minmax(0,1fr)] md:items-center"><div className="aspect-[16/9] overflow-hidden rounded-xl bg-slate-100"><img src={article.image} alt="" className="h-full w-full object-cover transition duration-300 group-hover:scale-105" /></div><div><h2 className="font-serif text-2xl font-semibold leading-tight text-navy transition group-hover:text-blue-700">{article.title}</h2><div className="mt-3 flex items-center gap-3 text-sm text-slate-500"><span>By {article.author}</span><span className="flex items-center gap-1"><CalendarDays size={14} /> {article.date}</span></div><p className="mt-4 max-w-2xl leading-7 text-slate-600">{article.excerpt}</p><span className="mt-4 inline-block text-sm font-semibold text-blue-600">Read article →</span></div></Link>)}</div><nav className="mt-10 flex items-center justify-center gap-2" aria-label="Article pages"><button onClick={() => setPage((current) => Math.max(1, current - 1))} disabled={page === 1} className="rounded-full border border-slate-300 p-2 text-navy disabled:text-slate-300"><ChevronLeft size={19} /></button>{Array.from({ length: pages }, (_, index) => index + 1).map((number) => <button key={number} onClick={() => setPage(number)} className={`h-10 w-10 rounded-full border text-sm font-semibold ${page === number ? 'border-blue-700 bg-blue-700 text-white' : 'border-slate-300 text-navy hover:border-blue-600'}`}>{number}</button>)}<button onClick={() => setPage((current) => Math.min(pages, current + 1))} disabled={page === pages} className="rounded-full border border-slate-300 p-2 text-navy disabled:text-slate-300"><ChevronRight size={19} /></button></nav></div></main>
}
