import React, { useState } from 'react'
import { ArrowLeft, CheckCircle2, Download, FileText, LockKeyhole, ShieldCheck, Sparkles, X } from 'lucide-react'

interface PDFViewerProps { onClose: () => void; reportName?: string }

const PDFViewer: React.FC<PDFViewerProps> = ({ onClose, reportName = 'CIBIL Report' }) => {
  const [downloaded, setDownloaded] = useState(false)
  const downloadReport = () => {
    const link = document.createElement('a')
    link.href = URL.createObjectURL(new Blob([`${reportName} Preview`], { type: 'application/pdf' }))
    link.download = `${reportName.replace(/\s+/g, '_')}.pdf`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(link.href)
    setDownloaded(true)
  }

  return <section className="min-h-screen bg-gradient-to-b from-slate-50 via-blue-50/40 to-white py-10 md:py-14">
    <div className="mx-auto max-w-6xl px-4"><div className="mb-8 flex items-center justify-between"><div><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-blue-600"><Sparkles size={14} /> Your report is ready</p><h1 className="mt-2 text-3xl font-bold text-navy md:text-4xl">Your {reportName}</h1><p className="mt-2 text-sm text-slate-500">A secure preview of your credit information report.</p></div><button onClick={onClose} className="rounded-full border border-slate-200 bg-white p-3 text-slate-500 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-200 hover:text-blue-600" aria-label="Close report"><X size={21} /></button></div>
      <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl shadow-blue-950/10"><div className="relative overflow-hidden bg-gradient-to-r from-[#073b86] via-blue-700 to-indigo-600 px-6 py-7 text-white md:px-10"><div className="absolute -right-12 -top-20 h-64 w-64 rounded-full bg-white/10" /><div className="relative flex flex-wrap items-center justify-between gap-5"><div className="flex items-center gap-4"><span className="rounded-2xl bg-white/15 p-3 backdrop-blur-sm"><FileText size={30} /></span><div><p className="text-sm text-blue-100">TransUnion CIBIL Limited</p><h2 className="text-xl font-bold md:text-2xl">Credit Information Report</h2></div></div><span className="inline-flex items-center gap-2 rounded-full border border-white/25 bg-white/10 px-3 py-1.5 text-xs font-semibold"><ShieldCheck size={15} /> Secure document</span></div></div>
        <div className="grid gap-8 p-5 md:grid-cols-[minmax(0,1fr)_260px] md:p-9"><div className="rounded-2xl bg-slate-100 p-4 shadow-inner md:p-7"><article className="mx-auto max-w-2xl rounded-lg bg-white p-6 shadow-lg shadow-slate-300/50 md:p-9"><div className="flex items-start justify-between border-b border-slate-200 pb-5"><div><p className="text-xs font-semibold uppercase tracking-widest text-blue-600">CIR / 2026</p><h3 className="mt-2 text-xl font-bold text-navy">Credit Information Report</h3><p className="mt-1 text-sm text-slate-500">Generated on {new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</p></div><FileText className="text-blue-500" size={29} /></div><div className="grid grid-cols-2 gap-x-8 gap-y-5 border-b border-slate-200 py-6 text-sm"><div><p className="text-slate-500">Report ID</p><p className="mt-1 font-semibold text-navy">CIB-4BE8B2CKI</p></div><div><p className="text-slate-500">Report status</p><p className="mt-1 inline-flex items-center gap-1 font-semibold text-emerald-600"><CheckCircle2 size={15} /> Generated</p></div><div><p className="text-slate-500">Full name</p><p className="mt-1 font-semibold text-navy">REPORT HOLDER</p></div><div><p className="text-slate-500">PAN</p><p className="mt-1 font-semibold text-navy">ABCDE••••F</p></div></div><div className="pt-6"><div className="flex items-center justify-between"><h4 className="font-semibold text-navy">Credit score overview</h4><span className="rounded-full bg-yellow-100 px-2.5 py-1 text-xs font-bold text-yellow-700">Good</span></div><div className="mt-4 flex items-end gap-5"><strong className="text-5xl leading-none text-navy">750</strong><div className="flex-1 pb-1"><div className="h-3 overflow-hidden rounded-full bg-gradient-to-r from-red-500 via-yellow-400 to-emerald-500"><div className="ml-[72%] h-full w-1.5 bg-navy shadow-[0_0_0_3px_white]" /></div><div className="mt-2 flex justify-between text-[10px] font-medium text-slate-400"><span>300</span><span>900</span></div></div></div></div><p className="mt-7 border-t border-slate-100 pt-5 text-center text-xs text-slate-400">Preview only · Download the PDF for the complete document.</p></article></div>
          <aside className="flex flex-col justify-between rounded-2xl border border-blue-100 bg-blue-50/70 p-6"><div><span className="inline-flex rounded-xl bg-white p-3 text-blue-600 shadow-sm"><Download size={23} /></span><h3 className="mt-5 text-xl font-bold text-navy">Download your report</h3><p className="mt-2 text-sm leading-6 text-slate-600">Save a PDF copy of your {reportName} for your records or to share with lenders.</p><ul className="mt-6 space-y-3 text-sm text-slate-600">{['Complete report summary', 'Secure PDF format', 'Available immediately'].map((item) => <li key={item} className="flex gap-2"><CheckCircle2 size={17} className="shrink-0 text-emerald-500" />{item}</li>)}</ul></div><div className="mt-8"><button onClick={downloadReport} className={`flex w-full items-center justify-center gap-3 rounded-xl px-6 py-3.5 text-sm font-semibold text-white shadow-lg transition ${downloaded ? 'bg-emerald-600 shadow-emerald-600/20' : 'bg-blue-600 shadow-blue-600/20 hover:-translate-y-0.5 hover:bg-blue-700'}`}><Download size={18} className="shrink-0" />{downloaded ? 'PDF Downloaded' : `Download ${reportName} PDF`}</button><p className="mt-4 flex items-center justify-center gap-1.5 text-center text-[11px] text-slate-500"><LockKeyhole size={12} /> Your document is protected and private.</p></div></aside>
        </div></div><button onClick={onClose} className="mx-auto mt-7 flex items-center gap-2 text-sm font-semibold text-blue-600 transition hover:-translate-x-1 hover:text-blue-800"><ArrowLeft size={17} /> Back to CIBIL Report</button>
    </div>
  </section>
}

export default PDFViewer
